# CNN Notes – Lesson 1: What is an Image?

## Key Points

• A computer does not see images like humans; it only sees numerical data.

• An image is a matrix (or tensor) of numbers representing pixel values.

• A pixel (Picture Element) is the smallest unit of a digital image.

• Every pixel stores information about brightness or color.

• A grayscale image has one channel, where each pixel has a value between 0 and 255.
  - 0 → Black
  - 255 → White
  - 1–254 → Shades of Gray

• A grayscale image is represented as a 2D matrix.

Shape:
(Height, Width)

Example:
(28, 28)

• An RGB image has three channels:
  - Red (R)
  - Green (G)
  - Blue (B)

• Each RGB pixel is represented as:
(R, G, B)

Example:
(255, 0, 0) → Red
(0, 255, 0) → Green
(0, 0, 255) → Blue

• Each RGB value ranges from 0 to 255.

• An RGB image is represented as a 3D tensor.

Shape:
(Height, Width, 3)

Example:
(224, 224, 3)

• Height represents the number of rows.

• Width represents the number of columns.

• Common image sizes:
  - 28 × 28
  - 64 × 64
  - 128 × 128
  - 224 × 224
  - 512 × 512

• CNNs process numerical pixel values instead of visual objects.

• CNNs learn features such as:
  - Edges
  - Corners
  - Lines
  - Textures
  - Shapes
  - Objects

• Images are commonly stored as NumPy arrays before being passed to deep learning models.

• The `.shape` attribute returns the dimensions of an image.

Examples:
Grayscale:
image.shape
Output:
(3, 3)

RGB:
image.shape
Output:
(224, 224, 3)

------------------------------------------------------------

## Important Shapes

Grayscale Image:
(Height, Width)

RGB Image:
(Height, Width, 3)

------------------------------------------------------------

## Important Definitions

Image:
A collection of pixels represented as numerical values.

Pixel:
The smallest unit of an image that stores brightness or color.

Grayscale Image:
An image containing a single channel of intensity values.

RGB Image:
An image containing three color channels: Red, Green, and Blue.

Channel:
A separate layer of image information.

Matrix:
A two-dimensional arrangement of numbers.

Tensor:
A multi-dimensional array used in deep learning to store data.

------------------------------------------------------------

## Interview Questions

1. What is a pixel?

2. What is the difference between a grayscale image and an RGB image?

3. Why does an RGB image have three channels?

4. What does the shape (224, 224, 3) represent?

5. Why do CNNs treat images as matrices instead of visual objects?

------------------------------------------------------------

## One-Line Summary

An image is a matrix (or tensor) of pixel values. A grayscale image has one channel, an RGB image has three channels, and CNNs learn patterns from these numerical values to recognize visual features and objects.

In [1]:
import numpy as np

# Create a 3×3 grayscale image
image = np.array([
    [0, 128, 255],
    [64, 192, 128],
    [255, 0, 64]
])

print("Image:")
print(image)

print("\nShape:", image.shape)

Image:
[[  0 128 255]
 [ 64 192 128]
 [255   0  64]]

Shape: (3, 3)
